### ISSUE TITLE
Error with python3.10-minimal, step 1

### ISSUE THREAD

**Issue by Whackjob** [simonlui/Docker_IPEX_ComfyUI#2]
Error on step 1.

[Errno 13] Permission denied: '/usr/lib/python3.10/__pycache__/__future__.cpython-310.pyc.140579518143088'dpkg: error processing package python3.10-minimal (--configure):
 installed python3.10-minimal package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3.10-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends --fix-missing     ${PYTHON} lib${PYTHON} python3-pip &&     apt-get clean &&     rm -rf  /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by simonlui** [comment]
Not my issue. Please search online before posting your issue. I literally found the answer in one minute of Googling. Follow this [StackOverflow answer](https://askubuntu.com/a/1482634). Let me know if it works.

**Comment by simonlui** [comment]
Can you confirm if your issue has been fixed? If not, I will be closing the issue.
