### ISSUE TITLE
The Docker container starts normally, but the browser cannot open it. 服务正常启动，但是浏览器访问不了

### ISSUE THREAD

**Issue by xwl5242** [simonlui/Docker_IPEX_ComfyUI#7]
<img width="1032" alt="0" src="https://github.com/user-attachments/assets/a445bc1d-566e-4a5a-a9c4-b1079b95ffe2">
<img width="465" alt="1" src="https://github.com/user-attachments/assets/dec6e742-f01d-452d-8d8f-0e195bd4b2f0">

**Comment by simonlui** [comment]
This seemed to have been opened and closed really quick. Was it because you didn't put in ComfyUI options like `--listen`?

**Comment by xwl5242** [comment]
Thank you.

> This seemed to have been opened and closed really quick. Was it because you didn't put in ComfyUI options like `--listen`?
